name: ocplist
description: A command-line app for scanning OpenCore config.plists.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  http: ^1.4.0
  path: ^1.9.1
  plist_parser: ^0.2.4
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
