name: ocplist Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  pages-deploy-CvpmCw:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Setup Pages
        uses: "actions/configure-pages@v5"
      - name: Upload artifact
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: "actions/deploy-pages@v4"
  dart-build-3Kd0BC:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        include:
          - os: ubuntu-latest
            output-name: ocplist-linux
          - os: windows-latest
            output-name: ocplist-windows.exe
          - os: macOS-latest
            output-name: ocplist-macOS
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Setup
        uses: "dart-lang/setup-dart@v1"
      - name: Cache Dependencies
        uses: "actions/cache@v4"
        with:
          path: ~/.pub-cache
          key: "${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}"
          restore-keys: "${{ runner.os }}-pub-"
      - name: Dart Build at /
        run: |-
          mkdir -p build
          dart pub get
          dart compile exe bin/main.dart -o build/${{ matrix.output-name }}
      - uses: "actions/upload-artifact@v4"
        with:
          name: "executables-${{ github.run_id }}-${{ matrix.output-name }}"
          path: "build/${{ matrix.output-name }}"
      - uses: "actions/upload-artifact@v4"
        with:
          name: "executables-alt-${{ github.run_id }}-${{ matrix.output-name }}"
          path: "build/${{ matrix.output-name }}"
  dart-build-alt-QKEg6O:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            output-name: ocplist
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Setup
        uses: "dart-lang/setup-dart@v1"
      - name: Cache Dependencies
        uses: "actions/cache@v4"
        with:
          path: ~/.pub-cache
          key: "${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}"
          restore-keys: "${{ runner.os }}-pub-"
      - name: Dart Build Extra at /
        run: |-
          mkdir -p build
          dart pub get
          dart compile kernel bin/main.dart -o build/${{ matrix.output-name }}.dill
